static class DashboardPageV2
{
    public const string ExtraScript = """
<script>fetch('/api/overview').then(r=>r.json()).then(o=>{const a=document.querySelector('#activity');if(a)a.innerHTML=o.events.map(e=>'<tr><td class="text-secondary small">'+new Date(e.occurredAtUtc).toLocaleString()+'</td><td><span class="badge bg-blue-lt">'+e.actor+'</span></td><td>'+e.type+'</td><td><code>'+e.entityId+'</code></td></tr>').join('');const card=document.createElement('div');card.className='col-12';card.innerHTML='<div class="card"><div class="card-header"><h2 class="card-title">Claims & evidence</h2><div class="text-secondary small">Verification freshness and support</div></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Claim</th><th>Status</th><th>Evidence</th><th>Findings</th></tr></thead><tbody>'+o.claims.map(c=>'<tr><td><strong>'+c.id+'</strong><div class="text-secondary small">'+c.statement+'</div></td><td><span class="badge bg-green-lt">'+(c.status||'UNKNOWN')+'</span></td><td>'+o.evidence.filter(e=>e.claimId===c.id).length+' record(s)</td><td>'+o.findings.filter(f=>f.status==='OPEN').length+' open</td></tr>').join('')+'</tbody></table></div></div>';document.querySelector('#records')?.before(card)}).catch(()=>{});</script>
""";
    public const string WorkScript = """
<script>fetch('/api/overview').then(r=>r.json()).then(o=>{const card=document.createElement('div');card.className='col-12';const tasks=o.tasks.filter(x=>x.status==='OPEN');const findings=o.findings.filter(x=>x.status==='OPEN');card.innerHTML='<div class="row row-cards"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="card-title">Work board</h2><span class="badge bg-blue-lt">'+tasks.length+' open</span></div><div class="list-group list-group-flush">'+(tasks.length?tasks.map(t=>'<div class="list-group-item"><div class="d-flex justify-content-between"><strong>'+t.id+'</strong><span class="badge bg-yellow-lt">'+(t.status||'OPEN')+'</span></div><div>'+t.title+'</div><div class="text-secondary small">Risk: '+(t.risk||'unclassified')+'</div></div>').join(''):'<div class="list-group-item text-secondary">No open tasks.</div>')+'</div></div></div><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="card-title">Findings & risk</h2><span class="badge bg-red-lt">'+findings.length+' open</span></div><div class="list-group list-group-flush">'+(findings.length?findings.map(f=>'<div class="list-group-item"><div class="d-flex justify-content-between"><strong>'+f.id+'</strong><span class="badge bg-red-lt">'+(f.severity||'UNKNOWN')+'</span></div><div>'+f.title+'</div><div class="text-secondary small">'+f.summary+'</div></div>').join(''):'<div class="list-group-item text-secondary">No open findings.</div>')+'</div></div></div></div>';document.querySelector('#records')?.before(card)}).catch(()=>{});</script>
""";
    public const string HandoffScript = """
<script>fetch('/api/overview').then(r=>r.json()).then(o=>{const h=o.handoffs[0],card=document.createElement('div');card.className='col-12';card.innerHTML='<div class="card"><div class="card-header"><h2 class="card-title">Latest handoff</h2><span class="badge bg-azure-lt">'+(h?.id||'None')+'</span></div><div class="card-body"><p class="mb-0">'+(h?.summary||'No handoff has been recorded yet.')+'</p></div></div>';document.querySelector('#records')?.before(card)}).catch(()=>{});</script>
""";
    public const string ExplorerScript = """
<script>fetch('/api/overview').then(r=>r.json()).then(o=>{const records=[...o.decisions,...o.tasks,...o.claims,...o.evidence,...o.findings,...o.handoffs];const card=document.createElement('div');card.className='col-12';card.innerHTML='<div class="card"><div class="card-header"><h2 class="card-title">Repository memory explorer</h2><div class="text-secondary small">Canonical records; SQLite is a disposable search index.</div></div><div class="card-body"><div class="row g-2 mb-3"><div class="col-auto"><select class="form-select" id="memoryFilter"><option value="all">All record types</option><option value="decisions">Decisions</option><option value="tasks">Tasks</option><option value="claims">Claims</option><option value="evidence">Evidence</option><option value="findings">Findings</option><option value="handoffs">Handoffs</option></select></div></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Type</th><th>ID</th><th>Title / summary</th><th>Status</th></tr></thead><tbody id="memoryRows"></tbody></table></div></div></div>';document.querySelector('#records')?.after(card);const rows=document.querySelector('#memoryRows'),filter=document.querySelector('#memoryFilter');function render(){const kind=filter.value;const groups=kind==='all'?Object.entries(o):[[kind,o[kind]||[]]];rows.innerHTML=groups.flatMap(([k,items])=>items.map(x=>'<tr><td><span class="badge bg-azure-lt">'+k+'</span></td><td><code>'+x.id+'</code></td><td>'+((x.title||x.statement||x.summary||'').slice(0,180))+'</td><td>'+(x.status||'—')+'</td></tr>')).join('')}filter.addEventListener('change',render);render()}).catch(()=>{});</script>
""";
    public const string WorkspaceScript = """
<script>Promise.all([fetch('/api/workspace').then(r=>r.json()),fetch('/api/status').then(r=>r.json())]).then(([items,status])=>{const card=document.createElement('div');card.className='col-12';card.innerHTML='<div class="card"><div class="card-header"><h2 class="card-title">Local workspace</h2><div class="text-secondary small">Registered projects stay local and isolated.</div></div><div class="card-body"><div class="input-group mb-3"><select class="form-select" id="workspaceSelect"><option value="">Select active project…</option></select><button class="btn btn-primary" id="workspaceUse">Use project</button></div><div class="list-group list-group-flush" id="workspaceRows"></div></div></div>';document.querySelector('#context')?.before(card);const rows=card.querySelector('#workspaceRows'),select=card.querySelector('#workspaceSelect');items.forEach(p=>{const option=document.createElement('option');option.value=p.root;option.textContent=p.name+' — '+p.root;select.appendChild(option);const row=document.createElement('div');row.className='list-group-item d-flex justify-content-between align-items-center';row.innerHTML='<span><strong></strong><br><code class="text-secondary small"></code></span><span class="badge bg-blue-lt">Local</span>';row.querySelector('strong').textContent=p.name;row.querySelector('code').textContent=p.root;rows.appendChild(row)});card.querySelector('#workspaceUse').onclick=async()=>{if(!select.value)return;const response=await fetch('/api/workspace/active',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({root:select.value})});if(response.ok)location.reload()}}).catch(()=>{});</script>
""";
    public const string Html = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ArifCE Dashboard</title><link rel="stylesheet" href="/assets/tabler.min.css">
  <style>body{background:#f4f6fa}.brand-logo{height:48px;width:auto}.hero{background:linear-gradient(135deg,#182d57,#2563ad);color:#fff}.hero p.lead,.hero .text-white-50,.hero .text-uppercase{color:#f4f8ff!important;opacity:.98}.metric{font-size:1.7rem;font-weight:700}pre{white-space:pre-wrap;max-height:330px;overflow:auto;background:#f8fafc;padding:1rem;border-radius:var(--tblr-border-radius)}.navbar-vertical .navbar-brand{margin-bottom:.75rem!important}.navbar-vertical .navbar-nav{padding-top:0!important}</style>
</head>
<body>
<div class="page">
  <aside class="navbar navbar-vertical navbar-expand-lg" data-bs-theme="light">
      <div class="container-fluid"><div class="navbar-brand navbar-brand-autodark"><a href="#overview" class="d-flex align-items-center"><img src="/assets/ArifCE.svg" class="brand-logo" alt="ArifCE"></a></div><div class="collapse navbar-collapse show"><ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link active" href="#overview"><span class="nav-link-title">Overview</span></a></li>
        <li class="nav-item"><a class="nav-link" href="#context"><span class="nav-link-title">Project context</span></a></li>
        <li class="nav-item"><a class="nav-link" href="#records"><span class="nav-link-title">Records</span></a></li>
        <li class="nav-item"><a class="nav-link" href="#search"><span class="nav-link-title">Search</span></a></li>
        <li class="nav-item mt-4"><div class="nav-link disabled"><span class="nav-link-title">Learn ArifCE</span></div></li>
        <li class="nav-item"><a class="nav-link" href="https://github.com/seekua/ArifCE/tree/master/docs" target="_blank" rel="noreferrer"><span class="nav-link-title">Documentation ↗</span></a></li>
        <li class="nav-item"><a class="nav-link" href="https://github.com/seekua/ArifCE/blob/master/docs/getting-started/quick-start.md" target="_blank" rel="noreferrer"><span class="nav-link-title">Quick start ↗</span></a></li>
        <li class="nav-item mt-4"><a class="nav-link" href="https://github.com/seekua/ArifCE" target="_blank" rel="noreferrer"><span class="nav-link-title">GitHub ↗</span></a></li>
      </ul></div></div>
  </aside>
  <div class="page-wrapper"><div class="page-body"><div class="container-xl py-4" id="overview">
      <section class="card hero mb-4"><div class="card-body p-4 p-md-5"><div class="row align-items-center"><div class="col-lg-8"><div class="text-uppercase text-white-50 small fw-bold mb-2">Local-first project intelligence</div><h1 class="display-5 mb-3">Keep the engineering story alive.</h1><p class="lead mb-4">Decisions, evidence, failed attempts, and handoffs stay with your repository so every agent can continue with context.</p><a class="btn btn-light" href="#context">Explore this project</a></div><div class="col-lg-4 d-none d-lg-block text-center"><div class="display-1">◈</div><div class="text-white-50">Your context. Your repository. Your control.</div></div></div></div></section>
      <div class="row row-cards mb-4" id="context"><div class="col-sm-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary">Project health</div><div class="metric" id="health">Loading…</div><div class="text-secondary small">from current state</div></div></div></div><div class="col-sm-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary">Tracked records</div><div class="metric" id="recordCount">—</div><div class="text-secondary small">canonical project memory</div></div></div></div><div class="col-sm-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary">Storage</div><div class="metric">Local</div><div class="text-secondary small">no cloud connection</div></div></div></div><div class="col-sm-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary">Continuity</div><div class="metric">Ready</div><div class="text-secondary small">for the next agent</div></div></div></div></div>
      <div class="row row-deck row-cards"><div class="col-lg-7"><div class="card h-100"><div class="card-header"><h2 class="card-title">Welcome to your project cockpit</h2></div><div class="card-body"><p>Understand what the repository knows before you change it.</p><div class="row g-3"><div class="col-md-6"><strong>Context first</strong><div class="text-secondary small">Read protocol, current state, and task memory.</div></div><div class="col-md-6"><strong>Evidence over confidence</strong><div class="text-secondary small">Trace claims to verification and findings.</div></div><div class="col-md-6"><strong>Handoffs that work</strong><div class="text-secondary small">Leave the next contributor a precise starting point.</div></div><div class="col-md-6"><strong>Searchable memory</strong><div class="text-secondary small">Find decisions, tasks, evidence, and failures.</div></div></div></div></div></div><div class="col-lg-5"><div class="card h-100"><div class="card-header"><h2 class="card-title">Current project status</h2></div><div class="card-body"><pre id="status">Loading…</pre></div></div></div>
      <div class="col-12"><div class="card"><div class="card-header"><h2 class="card-title">Agent activity</h2><div class="text-secondary small">Recent repository events</div></div><div class="card-body"><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>When</th><th>Actor</th><th>Event</th><th>Entity</th></tr></thead><tbody id="activity"><tr><td colspan="4">Loading…</td></tr></tbody></table></div></div></div></div>
      <div class="col-12" id="records"><div class="card"><div class="card-header"><h2 class="card-title">Recent records</h2></div><div class="card-body"><pre id="recordsData">Loading…</pre></div></div></div>
      <div class="col-12" id="search"><div class="card"><div class="card-header"><h2 class="card-title">Search project context</h2></div><div class="card-body"><div class="input-group"><input class="form-control" id="q" placeholder="Search decisions, tasks, evidence…"><button class="btn btn-primary" onclick="searchContext()">Search</button></div><pre id="results" class="mt-3">Type a query to search project memory.</pre></div></div></div></div>
    </div></div>
  </div>
</div>
<script>async function load(){try{const[s,r]=await Promise.all([fetch('/api/status'),fetch('/api/records?limit=30')]);const st=await s.json(),rec=await r.json();document.querySelector('#health').textContent=st.status||'Healthy';document.querySelector('#status').textContent=st.details||JSON.stringify(st,null,2);document.querySelector('#recordsData').textContent=JSON.stringify(rec,null,2);document.querySelector('#recordCount').textContent=rec.length;const o=await (await fetch('/api/overview')).json();const brief=document.createElement('div');brief.className='col-12';brief.innerHTML='<div class="card"><div class="card-header"><h2 class="card-title">Decision brief</h2></div><div class="card-body"><div class="row g-3"><div class="col-md-4"><div class="text-secondary">Latest decision</div><strong>'+(o.decisions[0]?.title||'None recorded')+'</strong></div><div class="col-md-4"><div class="text-secondary">Open work</div><strong>'+o.tasks.filter(x=>x.status==='OPEN').length+' task(s)</strong></div><div class="col-md-4"><div class="text-secondary">Open findings</div><strong>'+o.findings.filter(x=>x.status==='OPEN').length+' finding(s)</strong></div></div></div></div>';document.querySelector('#records').before(brief)}catch(e){document.querySelector('#status').textContent='Unable to load project status: '+e}}async function searchContext(){const q=document.querySelector('#q').value;if(!q)return;const r=await fetch('/api/search?q='+encodeURIComponent(q));document.querySelector('#results').textContent=JSON.stringify(await r.json(),null,2)}load()</script>
</body></html>
""";
}
