<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>arifce</ToolCommandName>
    <PackageId>ArifCE.Cli</PackageId>
    <Version>0.1.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ArifCE.Infrastructure/ArifCE.Infrastructure.csproj" />
    <None Include="../../README.md" Pack="true" PackagePath="/" Link="README.md" />
  </ItemGroup>
</Project>
