using ArifCE.Core;
using ArifCE.Infrastructure;

return await Cli.RunAsync(args);

internal static class Cli
{
    public static async Task<int> RunAsync(string[] args)
    {
        try
        {
            if (args.Length == 0 || args[0] is "-h" or "--help" or "help") { Help(); return 0; }
            var locator = new ProjectLocator(); var canonical = new CanonicalStore(); var journal = new JournalStore(); var index = new IndexStore(); var git = new GitInspector(); var service = new ProjectService(canonical, journal, index, git);
            var root = locator.FindRoot(Environment.CurrentDirectory); var command = args[0].ToLowerInvariant();
            switch (command)
            {
                case "init": case "adopt": Console.WriteLine($"Created {string.Join(Environment.NewLine + "Created ", await service.InitializeAsync(root, command == "adopt"))}"); break;
                case "status": Console.WriteLine(await service.StatusAsync(root)); break;
                case "doctor": Console.WriteLine(await service.DoctorAsync(root, args.Contains("--repair", StringComparer.Ordinal))); break;
                case "rebuild": await index.RebuildAsync(root); Console.WriteLine("Index rebuilt from canonical project intelligence."); break;
                case "search": Require(args, 2, "search <query>"); await Search(index, root, string.Join(' ', args[1..])); break;
                case "context": Require(args, 2, "context <task> [--budget N]"); await Context(index, root, args); break;
                case "task": await TaskCommand(service, root, args); break;
                case "decision": await DecisionCommand(service, root, args); break;
                case "attempt": await AttemptCommand(service, root, args); break;
                case "finding": await FindingCommand(service, root, args); break;
                case "review": await ReviewCommand(service, root, args); break;
                case "checkpoint": Console.WriteLine((await service.CheckpointAsync(root, Option(args, "--summary") ?? string.Join(' ', args[1..]))).Id); break;
                case "claim": await ClaimCommand(service, root, args); break;
                case "verify": Require(args, 2, "verify <claim-id> --command <command>"); var verified = await service.VerifyAsync(root, args[1], Option(args, "--command") ?? throw new ArgumentException("--command is required.")); Console.WriteLine($"{verified.Claim.Id}: {verified.Claim.Status} ({verified.Evidence.Id})"); break;
                case "architecture": await ArchitectureCommand(service, root, args); break;
                case "api": await ApiCommand(service, root, args); break;
                case "schema": await SchemaCommand(service, root, args); break;
                case "handoff": var handoff = await service.HandoffAsync(root); Console.WriteLine(handoff.Markdown); Console.WriteLine($"Saved {handoff.Id}"); break;
                case "why": Require(args, 2, "why <path-or-id>"); await Why(index, root, args[1]); break;
                case "refactor": await Refactor(service, canonical, root, args); break;
                default: throw new ArgumentException($"Unknown command '{args[0]}'. Run 'arifce help'.");
            }
            return 0;
        }
        catch (ArgumentException exception) { Console.Error.WriteLine($"Usage error: {exception.Message}"); return 2; }
        catch (Exception exception) { Console.Error.WriteLine($"Error: {exception.Message}"); return 1; }
    }

    private static async Task Search(IndexStore index, string root, string query) { foreach (var item in await index.SearchAsync(root, query)) Console.WriteLine($"{item.Path}\t{item.Score:F3}\t{item.Snippet.Replace(Environment.NewLine, " ")}"); }
    private static async Task Context(IndexStore index, string root, string[] args) { var marker = Array.IndexOf(args, "--budget"); var budget = marker >= 0 && marker + 1 < args.Length && int.TryParse(args[marker + 1], out var n) && n > 0 ? n : 8000; var task = string.Join(' ', args.Skip(1).Take(marker < 0 ? args.Length - 1 : marker - 1)); var terms = System.Text.RegularExpressions.Regex.Matches(task, "[A-Za-z0-9_]+", System.Text.RegularExpressions.RegexOptions.CultureInvariant).Select(x => x.Value).Distinct(StringComparer.OrdinalIgnoreCase).Take(12).ToArray(); if (terms.Length == 0) throw new ArgumentException("Context task must contain searchable terms."); var query = string.Join(" OR ", terms.Select(x => $"\"{x}\"")); var used = 0; Console.WriteLine($"Context Budget: {budget}\n\nIncluded"); foreach (var item in await index.SearchAsync(root, query, 50)) { var estimate = (int)Math.Ceiling(item.Snippet.Length / 4d); if (used + estimate > budget) continue; used += estimate; Console.WriteLine($"{item.Path}\t{estimate} tokens\tlexical term match, score {item.Score:F3}\n{item.Snippet}"); } Console.WriteLine($"\nEstimated total: {used}"); }
    private static async Task Why(IndexStore index, string root, string query) { var hits = await index.SearchAsync(root, $"\"{query.Replace("\"", "\"\"")}\"", 10); if (hits.Count == 0) Console.WriteLine("No recorded provenance or rationale was found. Historical rationale: unknown."); else foreach (var hit in hits) Console.WriteLine($"{hit.Path}: {hit.Snippet}"); }
    private static async Task TaskCommand(ProjectService service, string root, string[] args) { Require(args, 3, "task create <title> | task status <id> | task complete <id>"); switch (args[1]) { case "create": Console.WriteLine((await service.CreateTaskAsync(root, string.Join(' ', args[2..]), RiskLevel.Medium)).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetTaskAsync(root, args[2]) ?? throw new InvalidOperationException("Task not found."), JsonDefaults.Options)); break; case "complete": Console.WriteLine((await service.CompleteTaskAsync(root, args[2])).Status); break; default: throw new ArgumentException("Unknown task action."); } }
    private static async Task ClaimCommand(ProjectService service, string root, string[] args) { Require(args, 3, "claim create <statement> | claim status <id>"); switch (args[1]) { case "create": Console.WriteLine((await service.CreateClaimAsync(root, string.Join(' ', args[2..]), RiskLevel.Medium)).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetClaimAsync(root, args[2]) ?? throw new InvalidOperationException("Claim not found."), JsonDefaults.Options)); break; default: throw new ArgumentException("Unknown claim action."); } }
    private static async Task DecisionCommand(ProjectService service, string root, string[] args) { Require(args, 3, "decision create <title> --decision <text> [--rationale <text>] | decision status <id>"); switch (args[1]) { case "create": Console.WriteLine((await service.CreateDecisionAsync(root, args[2], Option(args, "--decision") ?? throw new ArgumentException("--decision is required."), Option(args, "--rationale"))).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetDecisionAsync(root, args[2]) ?? throw new InvalidOperationException("Decision not found."), JsonDefaults.Options)); break; default: throw new ArgumentException("Unknown decision action."); } }
    private static async Task AttemptCommand(ProjectService service, string root, string[] args) { Require(args, 3, "attempt record <task-id> <approach> --result <result> --reason <text> [--evidence <id>] | attempt status <id>"); switch (args[1]) { case "record": Require(args, 4, "attempt record <task-id> <approach> --result <result> --reason <text> [--evidence <id>]"); Console.WriteLine((await service.RecordAttemptAsync(root, args[2], args[3], Option(args, "--result") ?? throw new ArgumentException("--result is required."), Option(args, "--reason") ?? throw new ArgumentException("--reason is required."), Options(args, "--evidence"))).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetAttemptAsync(root, args[2]) ?? throw new InvalidOperationException("Attempt not found."), JsonDefaults.Options)); break; default: throw new ArgumentException("Unknown attempt action."); } }
    private static async Task FindingCommand(ProjectService service, string root, string[] args) { Require(args, 3, "finding create <title> --description <text> [--severity <level>] [--task <id>] [--path <path>] | finding status|resolve <id>"); switch (args[1]) { case "create": var severity = Enum.TryParse<RiskLevel>(Option(args, "--severity") ?? "Medium", true, out var parsed) ? parsed : throw new ArgumentException("--severity must be LOW, MEDIUM, HIGH, or CRITICAL."); Console.WriteLine((await service.CreateFindingAsync(root, args[2], Option(args, "--description") ?? throw new ArgumentException("--description is required."), severity, Option(args, "--task"), Option(args, "--path"))).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetFindingAsync(root, args[2]) ?? throw new InvalidOperationException("Finding not found."), JsonDefaults.Options)); break; case "resolve": Console.WriteLine((await service.ResolveFindingAsync(root, args[2])).Status); break; default: throw new ArgumentException("Unknown finding action."); } }
    private static async Task ReviewCommand(ProjectService service, string root, string[] args) { Require(args, 3, "review record <claim-id> --reviewer <agent> --verdict <verdict> --summary <text> [--finding <id>] | review status <id>"); switch (args[1]) { case "record": var verdictText = (Option(args, "--verdict") ?? throw new ArgumentException("--verdict is required.")).Replace("_", "", StringComparison.Ordinal); var verdict = Enum.TryParse<ReviewVerdict>(verdictText, true, out var parsed) ? parsed : throw new ArgumentException("--verdict must be AGREE, PARTIALLY_AGREE, DISAGREE, or INCONCLUSIVE."); Console.WriteLine((await service.RecordReviewAsync(root, args[2], Option(args, "--reviewer") ?? throw new ArgumentException("--reviewer is required."), verdict, Option(args, "--summary") ?? throw new ArgumentException("--summary is required."), Options(args, "--finding"))).Id); break; case "status": Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await service.GetReviewAsync(root, args[2]) ?? throw new InvalidOperationException("Review not found."), JsonDefaults.Options)); break; default: throw new ArgumentException("Unknown review action."); } }
    private static async Task ArchitectureCommand(ProjectService service, string root, string[] args) { Require(args, 3, "architecture check <claim-id> --forbid <reference> --path <source-path> [--forbid <reference> ...] [--path <source-path> ...]"); if (args[1] != "check") throw new ArgumentException("Unknown architecture action."); var result = await service.VerifyArchitectureBoundaryAsync(root, args[2], Options(args, "--forbid"), Options(args, "--path")); Console.WriteLine($"{result.Claim.Id}: {result.Claim.Status} ({result.Evidence.Id})"); }
    private static async Task ApiCommand(ProjectService service, string root, string[] args) { Require(args, 3, "api baseline|compare <assembly-path> --baseline <path> [--claim <claim-id>]"); var assembly = args[2]; var baseline = Option(args, "--baseline") ?? throw new ArgumentException("--baseline is required."); if (args[1] == "baseline") { await ApiSurfaceAnalyzer.WriteBaselineAsync(Path.GetFullPath(Path.Combine(root, baseline)), ApiSurfaceAnalyzer.Read(Path.GetFullPath(Path.Combine(root, assembly)))); Console.WriteLine($"API baseline written: {baseline}"); return; } if (args[1] != "compare") throw new ArgumentException("Unknown api action."); var claim = Option(args, "--claim") ?? throw new ArgumentException("--claim is required for api compare."); var result = await service.VerifyApiSurfaceAsync(root, claim, assembly, baseline); Console.WriteLine($"{result.Claim.Id}: {result.Claim.Status} ({result.Evidence.Id})"); }
    private static async Task SchemaCommand(ProjectService service, string root, string[] args) { Require(args, 3, "schema baseline|compare <database-path> --baseline <path> [--claim <claim-id>]"); var database = args[2]; var baseline = Option(args, "--baseline") ?? throw new ArgumentException("--baseline is required."); if (args[1] == "baseline") { await SqliteSchemaAnalyzer.WriteBaselineAsync(Path.GetFullPath(Path.Combine(root, baseline)), await SqliteSchemaAnalyzer.ReadAsync(Path.GetFullPath(Path.Combine(root, database)))); Console.WriteLine($"SQLite schema baseline written: {baseline}"); return; } if (args[1] != "compare") throw new ArgumentException("Unknown schema action."); var claim = Option(args, "--claim") ?? throw new ArgumentException("--claim is required for schema compare."); var result = await service.VerifySqliteSchemaAsync(root, claim, database, baseline); Console.WriteLine($"{result.Claim.Id}: {result.Claim.Status} ({result.Evidence.Id})"); }
    private static async Task Refactor(ProjectService service, CanonicalStore store, string root, string[] args) { Require(args, 2, "refactor start|status|checkpoint|resolve|workstream|safepoint|verify|finish|abandon"); switch (args[1]) { case "start": Require(args, 4, "refactor start <title> <objective> [--invariant <text>] [--inventory <item>] [--forbid <reference>]"); var invariants = Options(args, "--invariant"); var inventory = Options(args, "--inventory"); var guards = Options(args, "--forbid").Select(x => new RefactorGuard("forbiddenReference", x, true)).ToArray(); Console.WriteLine((await service.StartRefactorAsync(root, args[2], args[3], invariants, inventory, guards)).Id); break; case "status": Require(args, 3, "refactor status <id>"); Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(await store.ReadAsync<RefactorCampaign>(root, "refactors", args[2]) ?? throw new InvalidOperationException("Refactor not found."), JsonDefaults.Options)); break; case "checkpoint": Require(args, 4, "refactor checkpoint <id> <summary>"); Console.WriteLine((await service.CheckpointAsync(root, $"{args[2]}: {string.Join(' ', args[3..])}")).Id); break; case "resolve": Require(args, 4, "refactor resolve <id> <inventory-item>"); Console.WriteLine($"Remaining inventory: {(await service.ResolveRefactorInventoryAsync(root, args[2], args[3])).Inventory.Count}"); break; case "workstream": Require(args, 4, "refactor workstream <id> <name> --owner <agent> --path <path> [--path <path>]"); var owner = Option(args, "--owner") ?? throw new ArgumentException("--owner is required."); var paths = Options(args, "--path"); Console.WriteLine($"Workstreams: {(await service.AddRefactorWorkstreamAsync(root, args[2], args[3], owner, paths)).Workstreams!.Count}"); break; case "safepoint": Require(args, 4, "refactor safepoint <id> <name> [--note <text>]"); Console.WriteLine($"Safe points: {(await service.AddRefactorSafePointAsync(root, args[2], args[3], Option(args, "--note"))).SafePoints!.Count}"); break; case "verify": Require(args, 3, "refactor verify <id>"); var failures = await service.VerifyRefactorAsync(root, args[2]); Console.WriteLine(failures.Count == 0 ? "All configured deterministic refactor guards pass." : "Refactor verification failed:\n- " + string.Join("\n- ", failures)); if (failures.Count > 0) throw new InvalidOperationException("Refactor has blocking verification failures."); break; case "finish": Require(args, 3, "refactor finish <id>"); Console.WriteLine((await service.FinishRefactorAsync(root, args[2])).Status); break; case "abandon": Require(args, 3, "refactor abandon <id>"); Console.WriteLine((await service.AbandonRefactorAsync(root, args[2])).Status); break; default: throw new ArgumentException("Unknown refactor action."); } }
    private static string? Option(string[] args, string name) { var i = Array.IndexOf(args, name); return i >= 0 && i + 1 < args.Length ? args[i + 1] : null; }
    private static string[] Options(string[] args, string name) => args.Select((value, index) => (value, index)).Where(x => x.value == name && x.index + 1 < args.Length).Select(x => args[x.index + 1]).ToArray();
    private static void Require(string[] args, int length, string usage) { if (args.Length < length) throw new ArgumentException(usage); }
    private static void Help() => Console.WriteLine("ArifCE CLI\n\nCommands: init, adopt, status, doctor [--repair], rebuild, search, context, checkpoint, handoff, task create|status|complete, decision create|status, attempt record|status, finding create|status|resolve, claim create|status, verify, architecture check, api baseline|compare, schema baseline|compare, review record|status, why, refactor start|status|checkpoint|resolve|workstream|safepoint|verify|finish|abandon");
}
